**Aim:** Use numpy to perform all possible operations on matrices

In [33]:
import numpy as np
from numpy import linalg as LA

In [10]:
mat1 = np.array([[5, 10], [15, 20]])
mat2 = np.array([[1, 3], [5, 4]])

**Matrix Addition**

In [23]:
print(np.add(mat1,mat2))

[[ 6 13]
 [20 24]]


**Matrix Subtraction**

In [24]:
print(np.subtract(mat1,mat2))

[[ 4  7]
 [10 16]]


**Matrix Multiplication**

In [25]:
print(np.dot(mat1,mat2))

[[ 55  55]
 [115 125]]


**Summation of elemnts of matrix**

In [26]:
print(np.sum(mat1))

50


**Transpose of a matrix**

In [27]:
print(np.matrix.transpose(mat1))

[[ 5 15]
 [10 20]]


**Retrieve diagonal elements of matrix**

In [61]:
print("Diagonal elements : ",np.diag(mat1))
print("Elements above diagonal : ",np.diag(mat1,1))
print("Elemnts below diagonal : ",np.diag(mat1,-1))


Diagonal elements :  [ 5 20]
Elements above diagonal :  [10]
Elemnts below diagonal :  [15]


**Check if two matrices are equal**

In [64]:
print(np.array_equal(mat1,mat2))

False


**Sort Matrix Elements**

In [63]:
print(np.sort(mat2))

[[1 3]
 [4 5]]


**Trace of a matrix**

In [43]:
print(np.trace(mat1))

25


**Heighest and Lowest element in matrix**

In [48]:
print(np.max(mat1))
print(np.min(mat1))

20
5


**Identity Matrix Creation**

In [55]:
mat3=np.eye(2)
print(mat3)

[[1. 0.]
 [0. 1.]]


**Determinant of matrix**

In [35]:
print(LA.det(mat1))

-50.000000000000014


**Inverse of a matrix**

In [46]:
print(LA.inv(mat1))

[[-0.4  0.2]
 [ 0.3 -0.1]]


**Rank of matrix**

In [45]:
print(LA.matrix_rank(mat1))

2


**Eigen Values and Eigen vectors of Matrix**

In [34]:
print(LA.eigvals(mat1))

[-1.86140662 26.86140662]


In [36]:
print(LA.eig(mat1))

EigResult(eigenvalues=array([-1.86140662, 26.86140662]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


array([ 5, 20])